apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: {{ .DEPLOYMENT_NAME }}-autoscale
  labels:
    app: {{ .DEPLOYMENT_NAME }}-autoscale
    role: cron
spec:
  schedule: {{ quote .CRON }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .DEPLOYMENT_NAME }}-scaler
          containers:
            - name: {{ .DEPLOYMENT_NAME }}-autoscale
              image: {{ .IMAGE_NAME }}:{{ .IMAGE_TAG }}
              imagePullPolicy: IfNotPresent
              args: ["{{ .DEPLOYMENT_NAME }}", "{{ .REPLICAS }}"]
          restartPolicy: OnFailure