apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .DEPLOYMENT_NAME }}-scaler
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .DEPLOYMENT_NAME }}.scale
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "false"
rules:
  - apiGroups: [""]
    resources:
      - deployments/scale
    resourceNames:
      - {{ .DEPLOYMENT_NAME }}
    verbs:
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .DEPLOYMENT_NAME }}-scaler.{{ .DEPLOYMENT_NAME }}.scale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .DEPLOYMENT_NAME }}.scale
subjects:
- kind: ServiceAccount
  name: {{ .DEPLOYMENT_NAME }}-scaler